### PR TITLE
Added bitcoin and etherum white papers

### PR DESCRIPTION
**Pull request by salmanselu**
Added the original Bitcoin paper and etherum white paper to the written docs list

### CODE REVIEW

**Review by KukretiShubham — APPROVED** [review]
LGTM 👍🏼

**Review by vinzvinci — CHANGES_REQUESTED** [review]
Can you put these to **Whitepaper** category?

ex. 
## Category

| Title | Content |
| :-- | --- | 
| Original Bitcoin Paper | <a href="https://bitcoin.org/bitcoin.pdf">View</a> |
| Ethereum White Paper | <a href="https://ethereum.org/en/whitepaper/">View</a> |

I have question, do we really need these whitepaper to blockchain developer path?

**Comment by KukretiShubham** [comment]
ig you are right @vinzvinci, we don't need white paper for beginners, they might get confused. We can do that later, maybe.

**Comment by vinzvinci** [comment]
Yeah @KukretiShubham, I will close this since we don't need it yet. Members can ask on discord if ever needed.

**Pull request closed without merging**
